### ISSUE TITLE
causal mask when cross-attn

### ISSUE THREAD

**Issue by sukun1045** [lucidrains/MaMMUT-pytorch#1]
Hi, thanks for having this great repo. I just wonder if the causal mask should be used in the second forward pass when cross-attn is used. Or do I miss something here? Thank you

**Comment by lucidrains** [comment]
It has been a while and I don't remember the architecture proposed in this paper

however, it seems I always apply the causal mask here https://github.com/lucidrains/MaMMUT-pytorch/blob/main/mammut_pytorch/mammut_pytorch.py#L214

**Comment by sukun1045** [comment]
Sorry, I missed that. So it seems like the causal mask is used by default. Then in the first forward pass of `embed_text`, we should not use a causal mask because it is for contrastive purposes. I saw the `attn_mask` is initialized in the `embed_text` function but it seems like for preventing the cls token from attending to padding. Therefore, should we ignore the causal mask when calling `embed_text`?

**Comment by lucidrains** [comment]
you can actually use a causally masked text encoder for contrastive purposes if you pick out the eos token. Openai clip does this. In the case here, I'm doing a cls token with specialized masking

**Comment by lucidrains** [comment]
there are also rumors that causal attention networks yield better embeddings than non-causal. you hear this if you listen to a lot of Ilya's recent talks online

**Comment by sukun1045** [comment]
Got it. Yeah, it makes sense. Thanks again for your quick response :)
